import { GridColDef, GridRowsProp } from '@mui/x-data-grid'

export const mainColumns: GridColDef[] = [
  { field: 'header', headerName: 'Cechy główne', width: 150 },
  { field: 'ww', headerName: 'WW', type: 'number', width: 90, editable: true },
  { field: 'us', headerName: 'US', type: 'number', width: 90, editable: true },
  { field: 'k', headerName: 'K', type: 'number', width: 90, editable: true },
  {
    field: 'odp',
    headerName: 'Odp',
    type: 'number',
    width: 90,
    editable: true,
  },
  { field: 'zr', headerName: 'Zr', type: 'number', width: 90, editable: true },
  {
    field: 'int',
    headerName: 'Int',
    type: 'number',
    width: 90,
    editable: true,
  },
  { field: 'sw', headerName: 'SW', type: 'number', width: 90, editable: true },
  {
    field: 'ogd',
    headerName: 'Ogd',
    type: 'number',
    width: 90,
    editable: true,
  },
]

export const secondaryColumns: GridColDef[] = [
  { field: 'header', headerName: 'Cechy drugorzędne', width: 150 },
  { field: 'a', headerName: 'A', type: 'number', width: 90, editable: true },
  {
    field: 'zyw',
    headerName: 'Żyw',
    type: 'number',
    width: 90,
    editable: true,
  },
  { field: 's', headerName: 'S', type: 'number', width: 90, editable: true },
  {
    field: 'wt',
    headerName: 'Wt',
    type: 'number',
    width: 90,
    editable: true,
  },
  { field: 'sz', headerName: 'Sz', type: 'number', width: 90, editable: true },
  {
    field: 'mag',
    headerName: 'Mag',
    type: 'number',
    width: 90,
    editable: true,
  },
  { field: 'po', headerName: 'PO', type: 'number', width: 90, editable: true },
  {
    field: 'pp',
    headerName: 'PP',
    type: 'number',
    width: 90,
    editable: true,
  },
]

export const mainRows: GridRowsProp = [
  {
    id: 1,
    header: 'Początkowa',
    ww: 0,
    us: 0,
    k: 0,
    odp: 0,
    zr: 0,
    int: 0,
    sw: 0,
    ogd: 0,
  },
  {
    id: 2,
    header: 'Schemat Rozwoju',
    ww: 0,
    us: 0,
    k: 0,
    odp: 0,
    zr: 0,
    int: 0,
    sw: 0,
    ogd: 0,
  },
  {
    id: 3,
    header: 'Aktualna',
    ww: 0,
    us: 0,
    k: 0,
    odp: 0,
    zr: 0,
    int: 0,
    sw: 0,
    ogd: 0,
  },
]

export const secondaryRows: GridRowsProp = [
  {
    id: 1,
    header: 'Początkowa',
    a: 0,
    zyw: 0,
    s: Math.trunc(mainRows[0].k / 10),
    wt: 0,
    sz: 0,
    mag: 0,
    po: 0,
    pp: 0,
  },
  {
    id: 2,
    header: 'Schemat Rozwoju',
    a: 0,
    zyw: 0,
    s: 0,
    wt: 0,
    sz: 0,
    mag: 0,
    po: 0,
    pp: 0,
  },
  {
    id: 3,
    header: 'Aktualna',
    a: 0,
    zyw: 0,
    s: Math.trunc(mainRows[2].k / 10),
    wt: 0,
    sz: 0,
    mag: 0,
    po: 0,
    pp: 0,
  },
]
