import { GridRowsProp, GridColDef } from '@mui/x-data-grid';

export const mainColumns: GridColDef[] = [
  { field: 'header', headerName: 'Cechy główne', width: 150 },
  {
    field: 'melee',
    headerName: 'WW',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'ranged',
    headerName: 'US',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'sturdiness',
    headerName: 'K',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'endurance',
    headerName: 'Odp',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'agility',
    headerName: 'Zr',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'intelligence',
    headerName: 'Int',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'willPower',
    headerName: 'SW',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'refinement',
    headerName: 'Ogd',
    type: 'number',
    width: 90,
    editable: true,
  },
];

export const secondaryColumns: GridColDef[] = [
  { field: 'header', headerName: 'Cechy drugorzędne', width: 150 },
  {
    field: 'attacks',
    headerName: 'A',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'wounds',
    headerName: 'Żyw',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'strength',
    headerName: 'S',
    type: 'number',
    width: 90,
    editable: false,
  },
  {
    field: 'stamina',
    headerName: 'Wt',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'speed',
    headerName: 'Sz',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'magic',
    headerName: 'Mag',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'insanity',
    headerName: 'PO',
    type: 'number',
    width: 90,
    editable: true,
  },
  {
    field: 'fate',
    headerName: 'PP',
    type: 'number',
    width: 90,
    editable: true,
  },
];

export const mainRows: GridRowsProp = [
  {
    id: 1,
    header: 'Początkowa',
    melee: 0,
    ranged: 0,
    sturdiness: 0,
    endurance: 0,
    agility: 0,
    intelligence: 0,
    willPower: 0,
    refinement: 0,
  },
  {
    id: 2,
    header: 'Schemat Rozwoju',
    melee: 0,
    ranged: 0,
    sturdiness: 0,
    endurance: 0,
    agility: 0,
    intelligence: 0,
    willPower: 0,
    refinement: 0,
  },
  {
    id: 3,
    header: 'Aktualna',
    melee: 0,
    ranged: 0,
    sturdiness: 0,
    endurance: 0,
    agility: 0,
    intelligence: 0,
    willPower: 0,
    refinement: 0,
  },
];

export const secondaryRows: GridRowsProp = [
  {
    id: 1,
    header: 'Początkowa',
    attacks: 0,
    wounds: 0,
    strength: Math.trunc(mainRows[0].k / 10),
    stamina: 0,
    speed: 0,
    magic: 0,
    insanity: 0,
    fate: 0,
  },
  {
    id: 2,
    header: 'Schemat Rozwoju',
    attacks: 0,
    wounds: 0,
    strength: 0,
    stamina: 0,
    speed: 0,
    magic: 0,
    insanity: 0,
    fate: 0,
  },
  {
    id: 3,
    header: 'Aktualna',
    attacks: 0,
    wounds: 0,
    strength: Math.trunc(mainRows[2].k / 10),
    stamina: 0,
    speed: 0,
    magic: 0,
    insanity: 0,
    fate: 0,
  },
];
